name = "MvNormalCDF"
uuid = "37188c8d-bc69-4638-b057-733e744175ec"
keywords = ["cdf", "multivariate-normal", "distribution"]
desc = "Numerical Computation of Multivariate Normal Probabilities."
authors = ["PharmCat <v.s.arnautov@yandex.ru>", "Andrew Gough"]
version = "0.2.3"


[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Distributions = "0.20, 0.21, 0.22, 0.23, 0.24, 0.25"
FillArrays = "0.9, 0.10, 0.11, 0.12"
Primes = "0.5"
julia = "1"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[targets]
test = ["Test", "Distributions", "StableRNGs"]
